export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const CALCULATE_OVERALL_SPENDING = "CALCULATE_OVERALL_SPENDING";
export const SET_NEW_SPENT_LIMIT_DATA = "SET_NEW_SPENT_LIMIT_DATA";
export const SET_NEW_CATEGORY_DATA = "SET_NEW_CATEGORY_DATA";
export const UPDATE_SELECTED_CATEGORY = "UPDATE_SELECTED_CATEGORY";
