export const iconsData = [
  {
    name: "shirt",
    type: "ionicon",
    iconColor: "#DABB4F",
    innerCircleColor: "#FBF7EA",
    text: "Clothing",
    progress: 0.4,
    isClicked: false,
  },
  {
    name: "lipstick",
    type: "material-community",
    iconColor: "#5281AC",
    innerCircleColor: "#EAF0F5",
    text: "Beauty",
    progress: 0.2,
    isClicked: false,
  },
  {
    name: "volunteer-activism",
    type: "material-icon",
    iconColor: "#EF9E38",
    innerCircleColor: "#FDF3E7",
    text: "Health & Fitness",
    progress: 1,
    isClicked: false,
  },
  {
    name: "restaurant",
    type: "material-icon",
    iconColor: "#76A6D3",
    innerCircleColor: "#EFF4FA",
    text: "Food",
    progress: 0.5,
    isClicked: false,
  },
  {
    name: "home",
    type: "material-icon",
    iconColor: "#F0D0D4",
    innerCircleColor: "#FBF4F4",
    text: "Housing",
    progress: 0.7,
    isClicked: false,
  },
  {
    name: "camera",
    type: "font-awesome",
    iconColor: "#5ACCD1",
    innerCircleColor: "#EBF9F9",
    text: "Entertainment",
    progress: 0.2,
    isClicked: false,
  },
];
